# Generated by Django 5.2.7 on 2025-10-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('organization_admin', 'organization_admin'), ('organization_project_creator', 'organization_project_creator'), ('organization_team_creator', 'organization_team_creator'), ('organization_member', 'organization_member'), ('team_admin', 'team_admin'), ('team_member', 'team_member'), ('project_admin', 'project_admin'), ('project_member', 'project_member'), ('task_assigned', 'task_assigned')], max_length=64)),
                ('scope', models.CharField(choices=[('organization', 'organization'), ('team', 'team'), ('project', 'project'), ('task', 'task')], max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('scope', 'name'),
                'unique_together': {('name', 'scope')},
            },
        ),
    ]
