# Generated by Django 5.2.7 on 2025-10-31 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationinvitation',
            unique_together=set(),
        ),
    ]
