# Generated by Django 5.2.7 on 2025-10-31 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        ('roles', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_datetime', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ('expiration_datetime', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessor_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='tasks.task')),
                ('successor_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='tasks.task')),
            ],
            options={
                'ordering': ('predecessor_task',),
                'unique_together': {('predecessor_task', 'successor_task')},
            },
        ),
        migrations.CreateModel(
            name='TaskTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(limit_choices_to={'scope': 'task'}, on_delete=django.db.models.deletion.PROTECT, to='roles.role')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='tasks.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_team_memberships', to='teams.team')),
            ],
            options={
                'unique_together': {('task', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TaskUserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(limit_choices_to={'scope': 'task'}, on_delete=django.db.models.deletion.PROTECT, to='roles.role')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user_memberships', to='organizations.organizationmembership')),
            ],
            options={
                'unique_together': {('task', 'user')},
            },
        ),
    ]
